### PR TITLE
Added new devices to equipment checkboxes

### PR DESCRIPTION
**Pull request by Kavakuo**

### CODE REVIEW

**Comment by LisaR1** [comment]
Looks good. I think for PCR plates the format can then be discussed between "supplier" and diagnostic center :) (eg whether 96 wells or 384 wells)

**Comment by topialla** [comment]
Maybe we could encourage them to really post a link to the item at the manufacturers/distributers webpage, so everyone truly know what exactly they're looking for. And the actual Order number. In case of consumables this can truly make an important difference.

**Comment by LisaR1** [comment]
Like a description field @topialla?

**Comment by topialla** [comment]
Perhaps. Or we do it with radio buttons instead of check boxes and say, that they can ask for their most immediate need and can submit further requests after they have been validated?
I expect, one is looking for one special item when one needs something, thus they would be ok with this procedure?

This then leaves the question for offering resources (which should be as easy as possible) but for the requests this could solve the thing. 

what do you think from a UI/UX view about this @frwms ?

**Pull request merged**
